name: Package badges

on:
  push:
    branches: main

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest with coverage
        run: npm run coverage

      - name: Generate badge data
        id: generate-badge-data
        run: npm run generate-badge-data

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: coverage-badge.svg
          label: ${{ steps.generate-badge-data.outputs.coverage-label }}
          message: ${{ steps.generate-badge-data.outputs.coverage-message }}
          color: ${{ steps.generate-badge-data.outputs.coverage-color }}

      # Add steps to publish the package and badge if necessary
