name: Package badges

on:
  push:
    branches: main

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest with coverage
        run: npm run coverage

      - name: Generate our badge data
        run: npm run generate-badge-data
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_SECRET }}
          GIST_ID: ${{ secrets.GIST_ID }}

      # Add steps to publish the package and badge if necessary
